- name: check if zsh exists
  shell: command zsh -v
  register: zsh exists
  ignore_errors: true

- name: install zsh
  when: (zsh_exists is failed) and (ansible.distribution == "Ubuntu")
  become: true
  apt:
    name: zsh

- name: change default shell
  when: zsh_exists is failed
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: download Oh My Zsh install script
  when: zsh_exists is failed
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_omz.sh

- name: run Oh My Zsh installation script
  when: zsh_exists is failed
  command: sh /tmp/install_omz.sh --unattended
  register: omz_result
  failed_when: "'FAILED' in ohz_result.stderr"

- name: clone powerlevel10k repo
  when: zsh_exists is failed
  git:
    repo: git clone --depth=1 https://github.com/romkatv/powerlevel10k.gitnulnull
    dest: "{{ home_path }}/powerlevel10k"

- name: copy .p10k.zsh file
  when: zsh_exists is failed
  copy:
    src: ../files/.p10k.zsh
    dest: "{{ home_path }}/.p10k.zsh"

- name: copy .zshrc
  when: zsh_exists is failed
  copy:
    src: ../files/.zshrc
    dest: "{{ home_path }}/.zshrc"


